### ISSUE TITLE
Entity Linking model

### ISSUE THREAD

**Issue by tdt98** [HKUST-KnowComp/IFETEL#1]
Hello @hldai, thank you for sharing your great work. I am trying to rerun your model on my own language dataset but  I  was stuck at generating candidate-gen.pkl from Entity Linking model. I have looked for the model from the paper **_Unsupervised entity link-ing  with  abstract  meaning  representation_** but all provided links are dead. Could you please release your entity linking model? It would be great help for me. Thank you in advanced.

**Comment by hldai** [comment]
The provided entity linking method is very simple. It is only based on statistics from Wikipedia. 
title_wid_bisect_data is for mapping from Wikipedia titles to Wikipedia entry ids.
redirects_bisect_data  is for getting redirect page ids.
mstr_target_cnt_bisect_data is anchor link counts of surface forms (aka mention strings, or the surfaces of the anchors) to target Wikipedia entry ids.
entity_linked_cnts_dict is how many times the entity is the target of Wikipedia anchors.

In the EL algorithm, we basically are just looking for the entity with the largest commonness score.
