### ISSUE TITLE
question about "wid-types-figer.txt" file

### ISSUE THREAD

**Issue by janicewym** [HKUST-KnowComp/IFETEL#2]
Hi, author. Here I have a question about the "wid" in "wid-types-figer.txt". It seems not a id of wiki entity which start with "Q".  I had tried to add "Q" before id, and the entity which I searched from wikidata does not match the type in the file .So I'd like to know what does it mean?
Hope for your reply, thanks.

**Comment by hldai** [comment]
Hi. It's not the id that starts with "Q". It's an ID that can be found for each page in the Wikipedia dump.

**Comment by janicewym** [comment]
I got it. Thank you.



发自我的iPhone


------------------ Original ------------------
From: Hongliang Dai ***@***.***&gt;
Date: Fri,Oct 22,2021 3:28 PM
To: HKUST-KnowComp/IFETEL ***@***.***&gt;
Cc: janicewym ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [HKUST-KnowComp/IFETEL] question about "wid-types-figer.txt" file(Issue #2)





 
Hi. It's not the id that starts with "Q". It's an ID that can be found for each page in the Wikipedia dump.
